---

- name: Change root password
  user: name=root password={{root_password}}

- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=safe

- name: Install mosh
  apt: pkg=mosh state=installed

- name: Install git
  apt: pkg=git state=installed

- name: Install vim
  apt: pkg=vim state=installed

- name: Install fail2ban
  apt: pkg=fail2ban state=installed

- name: Install build-essential
  apt: pkg=build-essential state=installed

- name: Install coreutils
  apt: pkg=coreutils state=installed

- name: Add deployment user
  user: name=deploy password={{deploy_password}} shell=/bin/bash

- name: Add authorized deploy key
  authorized_key: user=deploy key="{{lookup('file', '/Users/doulos/.ssh/ansible_ssh_key.pub')}}"

- name: Remove sudo group rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: 
    - restart ssh

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: src=config/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

- name: Copy debconf selections so that Postfix can configure itself non-interactively
  copy: src=config/postfix_selections  dest=/tmp/postfix_selections

- name: Set up Postfix to relay mail
  command: debconf-set-selections /tmp/postfix_selections

- name: Install logwatch
  apt: pkg=logwatch state=installed

- name: Make logwatch mail $logwatch_email daily
  lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{logwatch_email}} --detail high" state=present create=yes

- name: Setup ufw
  #ufw: rule=allow port=22 proto=tcp name=SSH_Port
  shell: ufw allow 22/tcp

- name: Enable ufw
  shell: echo 'y' | ufw enable

- name: Disallow root SSH access
  lineinfile:  dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: 
    - restart ssh